baseURL = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = true
  centerTheme = true
  showGitInfo = true

[params.twitter]
  creator = "dehowell"
  site = "" # use if you have a Twitter handle for the site itself

[languages]
  [languages.en]
    languageName = "English"
    title = "David Howell"
    subtitle = "As unprincipled as the gods and as much a jack of all trades."
    owner = "David Howell"
    keywords = ""
    copyright = "Copyright 2020 David Howell"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "howell.io"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"